python downscaling_from_specific_dates.py "/projects/0/dfguu/users/edwinhs/data/from_niko_inundation_paper/simulation_result/channelStorage/Global_2000_landCover/netcdf/channelStorage_dailyTot.nc" "channelStorage" 1993-07-21 /scratch-shared/edwinhs/for_niko/output_folder_Global_2000_landCover_1993-07-21/ &
python downscaling_from_specific_dates.py "/projects/0/dfguu/users/edwinhs/data/from_niko_inundation_paper/simulation_result/channelStorage/Global_2000_landCover/netcdf/channelStorage_dailyTot.nc" "channelStorage" 1993-07-22 /scratch-shared/edwinhs/for_niko/output_folder_Global_2000_landCover_1993-07-22/ &
python downscaling_from_specific_dates.py "/projects/0/dfguu/users/edwinhs/data/from_niko_inundation_paper/simulation_result/channelStorage/Global_2000_landCover/netcdf/channelStorage_dailyTot.nc" "channelStorage" 1993-07-23 /scratch-shared/edwinhs/for_niko/output_folder_Global_2000_landCover_1993-07-23/ &
python downscaling_from_specific_dates.py "/projects/0/dfguu/users/edwinhs/data/from_niko_inundation_paper/simulation_result/channelStorage/Global_2000_landCover/netcdf/channelStorage_dailyTot.nc" "channelStorage" 1993-07-24 /scratch-shared/edwinhs/for_niko/output_folder_Global_2000_landCover_1993-07-24/ &
python downscaling_from_specific_dates.py "/projects/0/dfguu/users/edwinhs/data/from_niko_inundation_paper/simulation_result/channelStorage/Global_2000_landCover/netcdf/channelStorage_dailyTot.nc" "channelStorage" 1993-07-25 /scratch-shared/edwinhs/for_niko/output_folder_Global_2000_landCover_1993-07-25/ &
python downscaling_from_specific_dates.py "/projects/0/dfguu/users/edwinhs/data/from_niko_inundation_paper/simulation_result/channelStorage/Global_2000_landCover/netcdf/channelStorage_dailyTot.nc" "channelStorage" 1993-07-26 /scratch-shared/edwinhs/for_niko/output_folder_Global_2000_landCover_1993-07-26/ &
python downscaling_from_specific_dates.py "/projects/0/dfguu/users/edwinhs/data/from_niko_inundation_paper/simulation_result/channelStorage/Global_2000_landCover/netcdf/channelStorage_dailyTot.nc" "channelStorage" 1993-07-27 /scratch-shared/edwinhs/for_niko/output_folder_Global_2000_landCover_1993-07-27/ &
python downscaling_from_specific_dates.py "/projects/0/dfguu/users/edwinhs/data/from_niko_inundation_paper/simulation_result/channelStorage/Global_2000_landCover/netcdf/channelStorage_dailyTot.nc" "channelStorage" 1993-07-28 /scratch-shared/edwinhs/for_niko/output_folder_Global_2000_landCover_1993-07-28/ &
python downscaling_from_specific_dates.py "/projects/0/dfguu/users/edwinhs/data/from_niko_inundation_paper/simulation_result/channelStorage/Global_2000_landCover/netcdf/channelStorage_dailyTot.nc" "channelStorage" 1993-07-29 /scratch-shared/edwinhs/for_niko/output_folder_Global_2000_landCover_1993-07-29/ &
python downscaling_from_specific_dates.py "/projects/0/dfguu/users/edwinhs/data/from_niko_inundation_paper/simulation_result/channelStorage/Global_2000_landCover/netcdf/channelStorage_dailyTot.nc" "channelStorage" 1993-07-30 /scratch-shared/edwinhs/for_niko/output_folder_Global_2000_landCover_1993-07-30/ &
python downscaling_from_specific_dates.py "/projects/0/dfguu/users/edwinhs/data/from_niko_inundation_paper/simulation_result/channelStorage/Global_2000_landCover/netcdf/channelStorage_dailyTot.nc" "channelStorage" 1993-07-31 /scratch-shared/edwinhs/for_niko/output_folder_Global_2000_landCover_1993-07-31/ &
wait
