
# apply gumbel fits for surface water level

python 5b_gumbel_fits_apply_gumbel_parameters_for_surface_water_level.py /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp4p5_runs/gumbel_fits_surface_water_level/gfdl-esm2m_2010-2049/ /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp4p5_runs/extreme_values_surface_water_level/gfdl-esm2m_2010-2049/

python 5b_gumbel_fits_apply_gumbel_parameters_for_surface_water_level.py /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp4p5_runs/gumbel_fits_surface_water_level/hadgem2-es_2010-2049/ /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp4p5_runs/extreme_values_surface_water_level/hadgem2-es_2010-2049/

python 5b_gumbel_fits_apply_gumbel_parameters_for_surface_water_level.py /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp4p5_runs/gumbel_fits_surface_water_level/ipsl-cm5a-lr_2010-2049/ /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp4p5_runs/extreme_values_surface_water_level/ipsl-cm5a-lr_2010-2049/

python 5b_gumbel_fits_apply_gumbel_parameters_for_surface_water_level.py /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp4p5_runs/gumbel_fits_surface_water_level/miroc-esm-chem_2010-2049/ /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp4p5_runs/extreme_values_surface_water_level/miroc-esm-chem_2010-2049/

python 5b_gumbel_fits_apply_gumbel_parameters_for_surface_water_level.py /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp4p5_runs/gumbel_fits_surface_water_level/noresm1-m_2010-2049/ /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp4p5_runs/extreme_values_surface_water_level/noresm1-m_2010-2049/

python 5b_gumbel_fits_apply_gumbel_parameters_for_surface_water_level.py /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp8p5_runs/gumbel_fits_surface_water_level/gfdl-esm2m_2010-2049/ /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp8p5_runs/extreme_values_surface_water_level/gfdl-esm2m_2010-2049/

python 5b_gumbel_fits_apply_gumbel_parameters_for_surface_water_level.py /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp8p5_runs/gumbel_fits_surface_water_level/hadgem2-es_2010-2049/ /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp8p5_runs/extreme_values_surface_water_level/hadgem2-es_2010-2049/

python 5b_gumbel_fits_apply_gumbel_parameters_for_surface_water_level.py /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp8p5_runs/gumbel_fits_surface_water_level/ipsl-cm5a-lr_2010-2049/ /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp8p5_runs/extreme_values_surface_water_level/ipsl-cm5a-lr_2010-2049/

python 5b_gumbel_fits_apply_gumbel_parameters_for_surface_water_level.py /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp8p5_runs/gumbel_fits_surface_water_level/miroc-esm-chem_2010-2049/ /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp8p5_runs/extreme_values_surface_water_level/miroc-esm-chem_2010-2049/

python 5b_gumbel_fits_apply_gumbel_parameters_for_surface_water_level.py /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp8p5_runs/gumbel_fits_surface_water_level/noresm1-m_2010-2049/ /projects/0/aqueduct/users/edwinsut/flood_analyzer_analysis_rcp8p5_runs/extreme_values_surface_water_level/noresm1-m_2010-2049/

