
bash 0_analysis_for_rcp_runs/rcp6p0/extreme_value_analysis/extreme_value_analysis_rcp6p0_gfdl-esm2m.sh &
wait
bash 0_analysis_for_rcp_runs/rcp6p0/extreme_value_analysis/extreme_value_analysis_rcp6p0_hadgem2-es.sh &
bash 0_analysis_for_rcp_runs/rcp6p0/extreme_value_analysis/extreme_value_analysis_rcp6p0_ipsl-cm5a-lr.sh & 
wait
bash 0_analysis_for_rcp_runs/rcp6p0/extreme_value_analysis/extreme_value_analysis_rcp6p0_miroc-esm-chem.sh &
bash 0_analysis_for_rcp_runs/rcp6p0/extreme_value_analysis/extreme_value_analysis_rcp6p0_noresm1-m.sh &
wait
